from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query, status

from kgmemory.core.openapi import ORG_PROTECTED_RESPONSES
from kgmemory.orgs.auth import get_current_org
from kgmemory.orgs.models import Organization

from .monitor import acknowledge_alert, escalate_stale_alerts, get_alerts, run_monitor_loop

router = APIRouter(prefix="/monitor", tags=["monitor"])

ALERT_EXAMPLE = {
    "alert_id": "a1b2c3d4e5f6a7b8",
    "alert_type": "overdue_commitment",
    "subject": "dave",
    "project": "api",
    "person": "dave",
    "severity": "high",
    "message": "dave committed to 'ship auth module' due 2026-07-04 — overdue.",
    "evidence_fact_id": "abc-123",
    "status": "open",
    "created_at": "2026-07-08T12:00:00+00:00",
    "acknowledged_at": None,
}


@router.get(
    "/alerts",
    summary="List alerts",
    description=(
        "List alerts generated by the autonomous monitor loop. Alerts cover "
        "overdue commitments, engineer silence, single points of failure, and "
        "stale blockers. Filter by status: `open` (default), `acknowledged`, or `all`."
    ),
    responses={
        **ORG_PROTECTED_RESPONSES,
        200: {
            "description": "List of alerts",
            "content": {"application/json": {"example": [ALERT_EXAMPLE]}},
        },
    },
    openapi_extra={"security": [{"OrgAPIKey": []}]},
)
async def list_alerts_endpoint(
    alert_status: str = Query("open", pattern="^(open|acknowledged|all)$"),
    limit: int = Query(50, ge=1, le=200),
    org: Organization = Depends(get_current_org),
):
    return await get_alerts(org.graph_name, status=alert_status, limit=limit)


@router.post(
    "/scan",
    summary="Trigger a monitor scan",
    description=(
        "Manually trigger the autonomous monitor loop for this org. Scans for "
        "overdue commitments, silent engineers, single points of failure, and "
        "stale blockers. Generates Alert nodes for any new risks found. "
        "This normally runs on a schedule via the SAQ worker, but this endpoint "
        "lets you force a scan."
    ),
    responses={
        **ORG_PROTECTED_RESPONSES,
        200: {
            "description": "Scan results",
            "content": {
                "application/json": {
                    "example": {
                        "graph_name": "org_abc123",
                        "alerts_generated": 2,
                        "alerts": [ALERT_EXAMPLE],
                        "checked_at": "2026-07-08T12:00:00+00:00",
                        "elapsed_ms": 340,
                    }
                }
            },
        },
    },
    openapi_extra={"security": [{"OrgAPIKey": []}]},
)
async def scan_endpoint(org: Organization = Depends(get_current_org)):
    return await run_monitor_loop(org.graph_name, org=org)


@router.post(
    "/escalate",
    summary="Trigger escalation of stale alerts",
    description=(
        "Manually trigger escalation of alerts that have been open and "
        "unacknowledged for 24+ hours. Increases severity by one level and "
        "creates an escalation action. Normally runs every 6 hours via the "
        "SAQ worker cron schedule."
    ),
    responses={
        **ORG_PROTECTED_RESPONSES,
        200: {
            "description": "Escalation results",
            "content": {
                "application/json": {
                    "example": {
                        "graph_name": "org_abc123",
                        "escalated_count": 1,
                        "escalated": [ALERT_EXAMPLE],
                    }
                }
            },
        },
    },
    openapi_extra={"security": [{"OrgAPIKey": []}]},
)
async def escalate_endpoint(org: Organization = Depends(get_current_org)):
    return await escalate_stale_alerts(org.graph_name, org=org)


@router.post(
    "/alerts/{alert_id}/ack",
    summary="Acknowledge an alert",
    description=(
        "Mark an alert as acknowledged. Acknowledged alerts won't be re-created "
        "by the monitor loop unless the underlying risk re-occurs after a new "
        "fact is ingested."
    ),
    responses={
        **ORG_PROTECTED_RESPONSES,
        200: {
            "description": "Alert acknowledged",
            "content": {
                "application/json": {
                    "example": {
                        "alert_id": "a1b2c3d4e5f6a7b8",
                        "status": "acknowledged",
                        "acknowledged_at": "2026-07-08T13:00:00+00:00",
                    }
                }
            },
        },
        404: {"description": "Alert not found or already acknowledged"},
    },
    openapi_extra={"security": [{"OrgAPIKey": []}]},
)
async def ack_alert_endpoint(alert_id: str, org: Organization = Depends(get_current_org)):
    result = await acknowledge_alert(org.graph_name, alert_id)
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Alert not found or already acknowledged",
        )
    return result
